#!/usr/bin/env python3
"""Regenerates the 500 plain, checked-in do-nothing JUnit Jupiter test
classes under shared/src/main/scala/shared/. These are plain files, not
generated by sbt at build time -- this script is just how they were produced
once; re-run it only if you want to change the count.

Class names MUST match JUnit's ClassNameFilter.STANDARD_INCLUDE_PATTERN
("^(Test.*|.+[.$]Test.*|.*Tests?)$"), since a @Suite's discovery applies that
filter automatically (SuiteTestDescriptor#discover ->
filterStandardClassNamePatterns()). "GeneratedTest1" does NOT match (it
doesn't start or end with "Test"), so classes generated with that naming
scheme are silently excluded and every suite reports
NoTestsDiscoveredException regardless of whether the classloader race
happens -- that's why they're named "TestNNN" (starts with "Test") here.
"""

import os

COUNT = 500
DIR = os.path.join(os.path.dirname(__file__), "shared", "src", "main", "scala", "shared")

os.makedirs(DIR, exist_ok=True)

for i in range(1, COUNT + 1):
    path = os.path.join(DIR, f"Test{i}.scala")
    with open(path, "w") as f:
        f.write(f"""package shared

import org.junit.jupiter.api.Test

class Test{i} {{
  @Test def test(): Unit = ()
}}
""")

print(f"Wrote {COUNT} files to {DIR}")
