#!/usr/bin/env python3
"""Regenerates the 500 plain, checked-in do-nothing JUnit Jupiter test
classes under shared/src/main/scala/shared/. These are plain files, not
generated by sbt at build time -- this script is just how they were produced
once; re-run it only if you want to change the count."""

import os

COUNT = 500
DIR = os.path.join(os.path.dirname(__file__), "shared", "src", "main", "scala", "shared")

os.makedirs(DIR, exist_ok=True)

for i in range(1, COUNT + 1):
    path = os.path.join(DIR, f"GeneratedTest{i}.scala")
    with open(path, "w") as f:
        f.write(f"""package shared

import org.junit.jupiter.api.Test

class GeneratedTest{i} {{
  @Test def test(): Unit = ()
}}
""")

print(f"Wrote {COUNT} files to {DIR}")
